apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: yabtaour-app
  namespace: argocd
spec:
  destination:
    namespace: dev
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: git@github.com:yabtaour/yabtaour-argocd.git
    targetRevision: HEAD
    path: app
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
